all:
  children:
    jenkins:
      hosts:
        jenkins-node:
          ansible_host: 70.153.147.203
          ansible_user: ubuntu
    target:
      hosts:
        target-node:
          ansible_host: 70.153.151.129
          ansible_user: ubuntu