all:
  children:
    jenkins:
      hosts:
        jenkins-node:
          ansible_host: 65.52.160.212
          ansible_user: ubuntu
    target:
      hosts:
        target-node:
          ansible_host: 65.52.160.192
          ansible_user: ubuntu

        ansible_ssh_private_key_file: ~/.ssh/id_rsa
